
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
const inter = Inter({ subsets: ["latin"] });
import { Input } from "@/components/ui/input"
import Link from "next/link";
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};


export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={"min-h-screen w-full bg-white text-black flex"}>
                {/*side bar */}
                <div className="flex">
                    <div className="w-1/6 bg-gray-800 h-screen">
                        <div className="flex items-center justify-center h-16 bg-gray-900">
                            <span className="text-white text-lg font-semibold">Logo</span>
                        </div>
                        <nav className="mt-4">
                            <div className="flex items-center">
                            <Input type="text" placeholder="Search" 
                            className="py-2 px-4 border border-gray-300 rounded-l-md text-white w-1/2 mx-2
                           "/>
                            </div>
                            <Link href="/admin/user" className="block py-2 px-4 text-gray-300 hover:text-white">Users</Link>
                            <Link href="/admin/book" className="block py-2 px-4 text-gray-300 hover:text-white">Books</Link>
                            <Link href="/admin/order" className="block py-2 px-4 text-gray-300 hover:text-white">Orders</Link>
                            <Link href="#" className="block py-2 px-4 text-gray-300 hover:text-white">Profile</Link>
                        </nav>
                    </div>
                    <div className="w-5/6 bg-gray-100 h-screen">
                        {children}
                    </div>
                </div>
                {/*main page */}

            </body>
        </html>
    );
}
