import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/header";
import Footer from "@/components/layout/footer";
import { Toast } from "@radix-ui/react-toast";
import { Toaster } from "@/components/ui/toaster";
import { SessionProvider } from "next-auth/react";
import { Session } from "next-auth";
import { auth } from "@/auth";
import { ThemeProvider } from "next-themes";

const fontSans = Quicksand({
  subsets: ["latin"],
  weight: ["500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const session = await auth();
  if (session?.user.role === "ADMIN" || session?.user.role === "WAREHOUSE_STAFF") {
    return (
      <html lang="en">
        <body>
          <SessionProvider session={session}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
          </SessionProvider>
        </body>
      </html>
    );
  }
  return (
    <html lang="en">
      <body className={fontSans.className}>
        <SessionProvider session={session}>
          <div className={"min-h-screen flex flex-col justify-between"}>
            <Header session={session} />
            <main className="mt-24">{children}</main>
            <Footer />
          </div>
          <Toaster />
        </SessionProvider>
      </body>
    </html>
  );
}
